# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-15 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.IntegerField(default=-1000)),
                ('name', models.CharField(blank=True, max_length=122100, null=True)),
                ('text', models.CharField(blank=True, max_length=122100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.IntegerField(default=-1000)),
                ('name', models.CharField(blank=True, max_length=122100, null=True)),
                ('namec', models.CharField(blank=True, max_length=122100, null=True)),
                ('model', models.CharField(blank=True, max_length=122100, null=True)),
                ('modelc', models.CharField(blank=True, max_length=122100, null=True)),
                ('cc', models.CharField(blank=True, max_length=122100, null=True)),
                ('name1', models.CharField(blank=True, max_length=122100, null=True)),
                ('exprice', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=30, null=True)),
                ('start_date', models.CharField(blank=True, max_length=122100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.IntegerField(default=-1000)),
                ('name', models.CharField(blank=True, max_length=122100, null=True)),
                ('idv', models.CharField(blank=True, max_length=122100, null=True)),
                ('cover', models.CharField(blank=True, max_length=122100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('none', models.IntegerField(default=-1000)),
                ('loct', models.CharField(blank=True, max_length=122100, null=True)),
                ('loct_code', models.CharField(blank=True, max_length=122100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=122100, null=True)),
                ('city_code', models.CharField(blank=True, max_length=122100, null=True)),
            ],
        ),
    ]
